export const ASSISTANT_FIELD_LABELS: Record<string, string> = {
  about_title: 'כותרת אודות',
  about_subtitle: 'כותרת משנה',
  about_description: 'תיאור אודות',
  about_text: 'טקסט באזור ההירו',
  phone: 'טלפון',
  email: 'אימייל',
  contact_title: 'כותרת יצירת קשר',
  contact_subtitle: 'תת-כותרת יצירת קשר',
  name: 'שם החבילה',
  price_amount: 'מחיר',
  duration_text: 'משך זמן',
  includes: 'מה כלול',
  title: 'כותרת',
  subtitle: 'כותרת משנה',
  content: 'תוכן',
  question: 'שאלה',
  answer: 'תשובה',
  selected_theme: 'ערכת עיצוב',
  shoot_type: 'סוג צילום',
  hero_image: 'תמונת הירו',
  slug: 'כתובת אתר (Slug)',
  _delete_package: 'מחיקת חבילה',
  _delete_post: 'מחיקת פוסט',
  _delete_faq_item: 'מחיקת שאלה ותשובה',
  _delete_testimonial: 'מחיקת המלצה',
}

