'use client'

import Link from 'next/link'
import { galleryCardArrow, getSiteChromeCopy, type SiteLanguage } from '@/lib/site-language'
import { useRevealOnScroll } from '../shared/useRevealOnScroll'
import { ClassicSectionScript } from './ClassicSectionScript'
import { SectionTitle } from '../shared/SectionTitle'
import { ClassicPostCard, type ClassicHomepagePost } from './ClassicPostCard'
import styles from './ClassicPostsSection.module.css'

export type ClassicPostsSectionProps = {
  title: string
  posts: ClassicHomepagePost[]
  accentColor: string
  blogHref: string
  language: SiteLanguage
  hrefForPost: (postId: string) => string
}

const MAX_HOMEPAGE_POSTS = 3

/**
 * The homepage's "recent posts" teaser — sits between RecentPhotos and
 * Packages on the real page (see `${postsSectionHtml}` in
 * lib/homepage-themes/classic.ts, generated by
 * generateHomepagePostsSectionHTML in lib/homepage-posts-section.ts).
 */
export function ClassicPostsSection({
  title,
  posts,
  accentColor,
  blogHref,
  language,
  hrefForPost,
}: ClassicPostsSectionProps) {
  const { ref, revealed } = useRevealOnScroll<HTMLElement>()

  // Matches the old renderer: generateHomepagePostsSectionHTML returns ''
  // when there are no posts at all.
  if (posts.length === 0) return null

  const copy = getSiteChromeCopy(language)
  const arrow = galleryCardArrow(language)
  const display = posts.slice(0, MAX_HOMEPAGE_POSTS)

  return (
    <section
      ref={ref}
      className={`${styles.section} reveal ${revealed ? 'active' : ''}`}
    >
      <div className={styles.header}>
        <div className={styles.headerTitles}>
          <ClassicSectionScript color={accentColor}>Blog</ClassicSectionScript>
          <SectionTitle color="#1c1917">{title}</SectionTitle>
          <div className={styles.divider} style={{ background: accentColor }} />
        </div>
        <div className={styles.more}>
          <Link href={blogHref} className={styles.moreLink} style={{ color: accentColor }}>
            {copy.viewAllPosts}
            <span className={styles.moreArrow} aria-hidden="true">
              {arrow}
            </span>
          </Link>
        </div>
      </div>

      <div className={styles.grid}>
        {display.map((post) => (
          <ClassicPostCard key={post.id} post={post} href={hrefForPost(post.id)} accentColor={accentColor} />
        ))}
      </div>
    </section>
  )
}
