'use client'

import Link from 'next/link'
import { galleryCardArrow, getSiteChromeCopy, type SiteLanguage } from '@/lib/site-language'
import { useRevealOnScroll } from '../shared/useRevealOnScroll'
import { ClassicSectionScript } from './ClassicSectionScript'
import { SectionTitle } from '../shared/SectionTitle'
import { HomepageBlogCard, type HomepageBlogCardPost } from '../shared/HomepageBlogCard'
import { BlogCirclesGrid } from '../shared/BlogCirclesGrid'

/** Kept as a re-export so ClassicHomePage's `posts` prop type doesn't move. */
export type ClassicHomepagePost = HomepageBlogCardPost
import type { PostsDisplayStyle } from '@/lib/types/posts-display-style'
import styles from './ClassicPostsSection.module.css'

export type ClassicPostsSectionProps = {
  title: string
  posts: ClassicHomepagePost[]
  displayStyle: PostsDisplayStyle
  accentColor: string
  blogHref: string
  language: SiteLanguage
  hrefForPost: (postId: string) => string
}

const MAX_HOMEPAGE_POSTS = 4

/**
 * The homepage's "recent posts" teaser — sits between RecentPhotos and
 * Packages on the real page (see `${postsSectionHtml}` in
 * lib/homepage-themes/classic.ts, generated by
 * generateHomepagePostsSectionHTML in lib/homepage-posts-section.ts).
 */
export function ClassicPostsSection({
  title,
  posts,
  displayStyle,
  accentColor,
  blogHref,
  language,
  hrefForPost,
}: ClassicPostsSectionProps) {
  const { ref, revealed } = useRevealOnScroll<HTMLElement>()

  // Matches the old renderer: generateHomepagePostsSectionHTML returns ''
  // when there are no posts at all.
  if (posts.length === 0) return null

  const copy = getSiteChromeCopy(language)
  const arrow = galleryCardArrow(language)
  const display = posts.slice(0, MAX_HOMEPAGE_POSTS)

  return (
    <section
      ref={ref}
      className={`${styles.section} reveal ${revealed ? 'active' : ''}`}
    >
      <div className={styles.header}>
        <div className={styles.headerTitles}>
          <ClassicSectionScript color={accentColor}>Blog</ClassicSectionScript>
          <SectionTitle color="#1c1917">{title}</SectionTitle>
          <div className={styles.divider} style={{ background: accentColor }} />
        </div>
        <div className={styles.more}>
          <Link href={blogHref} className={styles.moreLink} style={{ color: accentColor }}>
            {copy.viewAllPosts}
            <span className={styles.moreArrow} aria-hidden="true">
              {arrow}
            </span>
          </Link>
        </div>
      </div>

      {displayStyle === 'circles' ? (
        <BlogCirclesGrid
          posts={display.map((post) => ({ ...post, excerpt: post.content, href: hrefForPost(post.id) }))}
          accentColor={accentColor}
          language={language}
        />
      ) : (
        <div className={styles.grid} data-count={display.length}>
          {display.map((post, index) => (
            <HomepageBlogCard
              key={post.id}
              post={post}
              href={hrefForPost(post.id)}
              accentColor={accentColor}
              index={index}
              total={display.length}
              language={language}
            />
          ))}
        </div>
      )}
    </section>
  )
}
