export {
  PREVIEW_MAX_MB as COVER_CARD_MAX_MB,
  PREVIEW_MAX_DIMENSION as COVER_CARD_MAX_DIMENSION,
  PREVIEW_QUALITY as COVER_CARD_QUALITY,
  PREVIEW_MAX_ITERATION as COVER_CARD_MAX_ITERATION,
  PREVIEW_COMPRESSION_OPTIONS as COVER_CARD_COMPRESSION_OPTIONS,
} from '@/lib/images/preview-compression'
